export const FETCH_FILTERS_REQUEST = 'FETCH_FILTERS_REQUEST';
export const FETCH_FILTERS_SUCCESS = 'FETCH_FILTERS_SUCCESS';
export const FETCH_FILTERS_FAILURE = 'FETCH_FILTERS_FAILURE';
export const TOGGLE_OCCUPATION = 'TOGGLE_OCCUPATION';
export const TOGGLE_TECH_STACK = 'TOGGLE_TECH_STACK';
export const TOGGLE_WORK_STYLE = 'TOGGLE_WORK_STYLE';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';